# Generated by Django 5.2.4 on 2025-07-07 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionhistory',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionhistory',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.pdfdocument'),
        ),
    ]
